name: Actualizacion Diaria Clima Pergamino

on:
  schedule:
    # 11:00 UTC = 08:00 AM Arg
    # 17:00 UTC = 02:00 PM Arg
    # 23:00 UTC = 08:00 PM Arg
    - cron: '0 11,17,23 * * *' 
  workflow_dispatch: # Permite ejecución manual

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install requests pandas

      - name: Ejecutar script de clima
        run: python actualizar_clima.py

      - name: Subir cambios al repo
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add meteo_daily.csv
          
          if git diff --staged --quiet; then
            echo "No hay datos nuevos para actualizar. Saltando commit."
          else
            git commit -m "Actualización programada: datos de clima agregados"
            git push
          fi
